### ISSUE TITLE
Just a little more contrast for the background of a selected line?

### ISSUE THREAD

**Issue by rcrooks** [makindajack/makinda-dark#1]
Hi @makindajack I really like the theme. Just one suggestion: it would be nice if the background of selected lines contrasted just a bit more with the general background color. 

The background for selections and search matches is fine.
<img width="1011" alt="2021-07-23_14-07-38" src="https://user-images.githubusercontent.com/619617/126823904-b3b33157-be01-4781-8e69-6ac404fdbe3d.png">

**Comment by makindajack** [comment]
@rcrooks I have fixed this, can you check if still you are facing the same issue and report back. Thanks

**Comment by rcrooks** [comment]
Thank you @makindajack !
